name: Pylint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      env: 
          GITHUB_TOKEN: ${{secrets.GH_ACCESS_TOKEN}}
          LOG_LEVEL: 1
          LOG_FILE: log.log
      working-directory: project-1/
      run: |
        ./run install
    - name: Run Test
      env: 
        GITHUB_TOKEN: ${{secrets.GH_ACCESS_TOKEN}}
        LOG_LEVEL: 1
        LOG_FILE: log.log
      working-directory: project-1/
  
      run: |
        ./run test
